/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "surface-container-highest": "#27272a",
        "tertiary-container": "#18181b",
        "tertiary": "#09090b",
        "on-tertiary-container": "#a1a1aa",
        "secondary": "#a855f7",
        "tertiary-fixed-dim": "#a1a1aa",
        "tertiary-fixed": "#e4e4e7",
        "secondary-fixed-dim": "#c084fc",
        "surface-variant": "#18181b",
        "surface-container": "#09090c",
        "surface": "#050505",
        "secondary-fixed": "#e9d5ff",
        "secondary-container": "#3b0764",
        "primary-fixed": "#fafafa",
        "background": "#030303",
        "on-primary-fixed": "#09090b",
        "inverse-primary": "#a1a1aa",
        "surface-container-low": "#050505",
        "primary": "#ffffff",
        "on-surface-variant": "#a1a1aa",
        "on-primary-fixed-variant": "#71717a",
        "outline-variant": "#1e1e24",
        "error": "#ef4444",
        "inverse-surface": "#fafafa",
        "on-background": "#fafafa",
        "surface-tint": "#a855f7",
        "on-surface": "#fafafa",
        "primary-container": "#18181b",
        "on-error-container": "#fca5a5",
        "on-tertiary-fixed-variant": "#71717a",
        "surface-container-lowest": "#010101",
        "on-secondary-fixed-variant": "#a855f7",
        "surface-dim": "#18181b",
        "on-tertiary-fixed": "#fafafa",
        "outline": "#27272a",
        "on-error": "#ffffff",
        "on-primary-container": "#a1a1aa",
        "surface-container-high": "#121215",
        "error-container": "#7f1d1d",
        "on-secondary-fixed": "#3b0764",
        "inverse-on-surface": "#09090b",
        "on-tertiary": "#fafafa",
        "primary-fixed-dim": "#a1a1aa",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#f5f3ff",
        "on-primary": "#09090b",
        "surface-bright": "#121214"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "md": "16px",
        "margin": "32px",
        "3xl": "64px",
        "gutter": "24px",
        "xl": "32px",
        "sm": "8px",
        "base": "4px",
        "2xl": "48px",
        "lg": "24px",
        "xs": "4px"
      },
      "fontFamily": {
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "headline-lg": ["28px", {"lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-xl": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "code-sm": ["13px", {"lineHeight": "18px", "fontWeight": "400"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
