/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "surface-container-highest": "#e4e2e4",
        "tertiary-container": "#271901",
        "tertiary": "#000000",
        "on-tertiary-container": "#98805d",
        "secondary": "#4648d4",
        "tertiary-fixed-dim": "#dec29a",
        "tertiary-fixed": "#fcdeb5",
        "secondary-fixed-dim": "#c0c1ff",
        "surface-variant": "#e4e2e4",
        "surface-container": "#f0edef",
        "surface": "#fcf8fa",
        "secondary-fixed": "#e1e0ff",
        "secondary-container": "#6063ee",
        "primary-fixed": "#dae2fd",
        "background": "#fcf8fa",
        "on-primary-fixed": "#131b2e",
        "inverse-primary": "#bec6e0",
        "surface-container-low": "#f6f3f5",
        "primary": "#000000",
        "on-surface-variant": "#45464d",
        "on-primary-fixed-variant": "#3f465c",
        "outline-variant": "#c6c6cd",
        "error": "#ba1a1a",
        "inverse-surface": "#303032",
        "on-background": "#1b1b1d",
        "surface-tint": "#565e74",
        "on-surface": "#1b1b1d",
        "primary-container": "#131b2e",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#574425",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#2f2ebe",
        "surface-dim": "#dcd9db",
        "on-tertiary-fixed": "#271901",
        "outline": "#76777d",
        "on-error": "#ffffff",
        "on-primary-container": "#7c839b",
        "surface-container-high": "#eae7e9",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#07006c",
        "inverse-on-surface": "#f3f0f2",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#bec6e0",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#fffbff",
        "on-primary": "#ffffff",
        "surface-bright": "#fcf8fa"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "md": "16px",
        "margin": "32px",
        "3xl": "64px",
        "gutter": "24px",
        "xl": "32px",
        "sm": "8px",
        "base": "4px",
        "2xl": "48px",
        "lg": "24px",
        "xs": "4px"
      },
      "fontFamily": {
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "headline-lg": ["28px", {"lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-xl": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "code-sm": ["13px", {"lineHeight": "18px", "fontWeight": "400"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
